name: Webhook Triggered Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks to complete
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: dbt Cloud
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 3600

      - name: Print check information
        if: steps.wait-for-check.outputs.conclusion == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });

            const targetCheck = checks.check_runs.find(check => check.name === 'dbt Cloud');

            if (targetCheck) {
              console.log('Check Information:');
              console.log(JSON.stringify(targetCheck, null, 2));
            } else {
              console.log('Target check not found');
            }
