name: Webhook Triggered Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Wait for 10 seconds
      - name: Wait for 10 seconds
        run: sleep 10

      # Step 2: Print out all checks for the PR
      - name: Print all checks on the PR
        uses: actions/github-script@v6
        with:
          script: |
            const pr = github.context.payload.pull_request;
            if (!pr) {
              core.setFailed("This action only works on pull request events.");
              return;
            }

            const { data: checks } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            console.log("Checks on this PR:");
            checks.check_runs.forEach(check => {
              console.log(`${check.name}: ${check.status} - ${check.conclusion}`);
            });
