name: Webhook Triggered Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Wait for 10 seconds
      - name: Wait for 10 seconds
        run: sleep 10

      # Step 2: Print out all checks for the PR
      - name: Get PR checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          REPO_FULL_NAME=${{ github.repository }}

          CHECKS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_FULL_NAME/pulls/$PR_NUMBER/check-runs")

          echo "Checks for PR #$PR_NUMBER:"
          echo "$CHECKS" | jq -r '.check_runs[] | "- \(.name): \(.status) (\(.conclusion))"'
