name: Webhook Triggered Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Wait for 10 seconds
      - name: Wait for 10 seconds
        run: sleep 10

      # Step 2: Print out all checks for the PR
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          REPO_FULL_NAME=${{ github.repository }}

          echo "Checks and Statuses for PR #$PR_NUMBER:"

          # Fetch check runs
          CHECK_RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_FULL_NAME/pulls/$PR_NUMBER/check-runs")

          # Fetch statuses
          STATUSES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_FULL_NAME/commits/${{ github.event.pull_request.head.sha }}/status")

          # Process check runs
          echo "Check Runs:"
          CHECK_RUNS_COUNT=$(echo "$CHECK_RUNS" | jq '.total_count')
          if [ "$CHECK_RUNS_COUNT" = "0" ] || [ "$CHECK_RUNS_COUNT" = "null" ]; then
            echo "No check runs found."
          else
            echo "$CHECK_RUNS" | jq -r '.check_runs[] | "- \(.name): \(.status) (\(.conclusion // "N/A"))"'
          fi

          echo ""

          # Process statuses
          echo "Status Checks:"
          STATUS_COUNT=$(echo "$STATUSES" | jq '.total_count')
          if [ "$STATUS_COUNT" = "0" ] || [ "$STATUS_COUNT" = "null" ]; then
            echo "No status checks found."
          else
            echo "$STATUSES" | jq -r '.statuses[] | "- \(.context): \(.state)"'
          fi

          # If both are empty, show raw responses for debugging
          if [ "$CHECK_RUNS_COUNT" = "0" ] && [ "$STATUS_COUNT" = "0" ]; then
            echo ""
            echo "No checks or statuses found. Raw responses for debugging:"
            echo "Check Runs API Response:"
            echo "$CHECK_RUNS" | jq '.'
            echo ""
            echo "Statuses API Response:"
            echo "$STATUSES" | jq '.'
          fi
